# Generated by Django 4.0.4 on 2022-05-18 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('_updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('address', models.CharField(max_length=512, null=True, verbose_name='address')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
                ('symbol', models.CharField(max_length=256, verbose_name='symbol')),
                ('price_in_dollars', models.FloatField(default=0, null=True, verbose_name='price in dollars')),
                ('network', models.CharField(default='Ethereum', max_length=256, verbose_name='network')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
